### PR TITLE
Q-Chem basic atom output reader, fill widget menu and atom selector

### PR DESCRIPTION
**Pull request by herbertludowieg**
Added a basic Q-Chem output reader that, so far, can only read the atomic positions from the different frames. Modeled after the Gaussian output reader.
Fill widget menu is an added menu on the GUI under Fill where a user can select different viewing modes for the atoms like Ball and Stick, Van der Waals spheres and Covalent Spheres. Appropriate changes have been made to the isotopes.json file in exa.
Added an atom selector where one can select any pair of atoms and it can measure the distance between the two atoms. Added as a new menu option on the GUI under Distance. Requires much user interaction, but, it only sends back a signal when a click event is triggered. It automatically updates a traitlet value as suggested by @tjduigna and the data is read on the Python side of things. Works with multiple scenes, tested with three scenes, and the output table is a concatenated DataFrame for all three scenes. Future development would include a self-updating table that can be dynamic and take whatever data as a request for atomic positions, distances, tensor values, etc.

### CODE REVIEW

**Comment by tjduigna** [comment]
You may want to modify the .travis.yml file to install exa from the open PR you have so that travis doesn't fail with "AttributeError: 'Element' object has no attribute 'cov_radius'".  Then you will be able to see if there is anything else to fix.

**Comment by herbertludowieg** [comment]
Should I close this PR and re-open it so that travis can re-run? I looked online on how to extract a package from a PR and found a forum saying that it wasn't implemented since it can cause errors with multiple PR's.

**Comment by herbertludowieg** [comment]
I don't know why the numbafy is failing I put the code I used on the exa PR but just for completeness here it is,
```
from exa.util.nbvars import numbafy
import sympy as sy
import numpy as np

arr = np.random.rand(10).astype("float32")
sig3 = ["float32(float32, float32, float32)"]

x, y, z = sy.symbols("x y z")
fn = sy.acos(x)/y + sy.exp(-y) + sy.Mod(z, 2)
func = numbafy(fn, (x, y, z), compiler="vectorize", signatures=sig3)
result = func(arr, arr, arr)
check = np.arccos(arr)/arr + np.exp(-arr) + np.mod(arr, 2)
print("arr = {}, sig3 = {}".format(arr, sig3))
print(np.allclose(result, check) == True)
```

**Comment by herbertludowieg** [comment]
Passes all tests done locally with pytest on exa/util/tests directory

**Comment by herbertludowieg** [comment]
Fails when trying to import exa/core/parser.py in qe/core/base.py as it is commented out. I don't see any calls to the qe/core/base.py with grep on exatomic. Is it safe to assume that we can comment out this file?

**Comment by avmarchenko** [comment]
You've removed some (unused?) functionality that is supposed to make parsing QE output easier; most of this can be performed using alternative existing API such as XYZ and parse_dynamics. Leave it commented for now (i.e. don't delete).

Can you please fix the docs error (should be super quick)
```
/home/travis/build/exa-analytics/exatomic/exatomic/core/universe.py:docstring of exatomic.core.universe.Universe:40:more than one target found for cross-reference 'MOMatrix': exatomic.core.orbital.MOMatrix, exatomic.nbo.output.MOMatrix
```

Once Travis builds properly, I'll merge this PR.

**Comment by herbertludowieg** [comment]
The quick fix that I am trying out is to just change the name of the MOMatrix class in nbo to something like nboMOMatrix. I ran the pytest --cov and the other tests in travis and passed locally. Just wanted to ask if that was the fix you were thinking of. I guess for the future it may be worthwhile to see if there is some way to make a conditional statement for nbo and all other MOMatrix parsing.

**Comment by avmarchenko** [comment]
Thanks for this contribution. I think we can merge this PR. I look forward to seeing more contributions!

**Comment by herbertludowieg** [comment]
The interfaces.tens was something I implemented to read tensors mirroring what was being done in the XYZ file reader. We ended up using the core.tensor to do this task which looks to be much better.

**Pull request merged**
