### PR TITLE
Frequency visualization

### LINKED ISSUE #181: Frequency visualization
**Is your feature request related to a problem? Please describe.**
This has been on my mind to do for a long time now. I think it would be great if we could add a frequency mode visualizer in the `UniverseWidget`. I often use ADFview which as far as we have been able to see does not have a frequency visualizer and since we don't have access to GaussView the Gaussian code parser could also benefit from this greatly.

**Describe the solution you'd like**
A visualizer that can both show the normal mode displacements as an animation and the vectors as arrows. This would probably have to be done on the fly when selecting the specific normal mode.

**Describe alternatives you've considered**
The animation is easy to get around with the current implementation as we can add frames to the atom table and as long as we re-make the universe we can visualize the normal mode displacements.

### PR DESCRIPTION
**Pull request by herbertludowieg**
Added functionality to visualize the frequency normal mode displacement vectors on the universe widget.

Closes #181 

Test code:
``` python
from exatomic.base import resource, list_resources
from exatomic.gaussian import Fchk
from exatomic.widgets import UniverseWidget as UW
ed = Fchk(resource('g16-methyloxirane-def2tzvp-freq.fchk')).to_universe()
UW(ed)
```

**EDIT** 06/12/2021:
----------------------------
  - Can now visualize the normal mode displacements

To Do:
 - [x] Add normal mode visualization
 - [ ] Clean up and optimize code.
 - [ ] Add the arrows back in
 - [ ] Add option to change from arrows to animation
 - [ ] Add high quality arrows

### CODE REVIEW

**Comment by tjduigna** [comment]
Hey I appreciate that this PR additionally addresses adding arrows to the `UniverseWidget` and I am not sure how you plan to implement animating the normal modes but I am wondering if you have ever stumbled on `exatomic.core.atom.add_vibrational_mode` which attempted a naive (and probably more inefficient) approach to frequency visualizations by computing all the nuclear displacements on the python side and then letting the default frame-based animation loop take responsibility for it all.

I don't think I ever added any consideration of scaling to get an appropriate time-scale as a function of x fps animation speed. Also, it merely constructs the frames to follow a sinusoidal trajectory along the displacement vectors (for a few loops) whereas maybe it's more appropriate for the frames to be constructed using a linear trajectory.

**Comment by herbertludowieg** [comment]
I did come across that function and for some time that was the way I have been doing it. Something I wanted to explore to animate the normal modes would be to generate them on the python side and have JS track the frames and do it in a similar way to the animation for the frames.

I would probably try to just calculate 20 frames. I noticed that was smooth enough.

**Comment by avmarchenko** [comment]
Hey @herbertludowieg what is the status of this PR? From the first comment, it looks like its still a WIP right? Please don't hesitate to request reviews when you think its ready.

**Comment by avmarchenko** [comment]
@herbertludowieg  @tjduigna what are we thinking with respect to this PR?

**Pull request closed without merging**
