### PR TITLE
Va input generator bug

### LINKED ISSUE #169: Va input generator is not working
**Describe the bug**
Grabbing the wrong number of frequency modes and atoms in `exatomic.va.GenInput._gen_displaced`.

**To Reproduce**
```
from exatomic.base import resource
from exatomic.adf import Output
from exatomic.va import GenInput

uni = Output(resource("adf-ch4-opt-freq.out")).to_universe()
inputs = GenInput(uni=uni, delta_type=2)
print(inputs.disp.to_string())
```

**Expected behavior**
Gives the displaced structures.

### PR DESCRIPTION
**Pull request by herbertludowieg**
Very simple patch which closes #169.

### CODE REVIEW

**Comment by herbertludowieg** [comment]
Will look into why the tests are failing either later today or over the weekend and the PR will be ready to get merged in.

**Comment by avmarchenko** [comment]
It appears that fields (columns) are not the correct type for certain tests to pass. The appear as categorical when they should be a lower type it seems?

**Comment by herbertludowieg** [comment]
Maybe, I wonder if it's similar to what we had to do in PR #147 where we had to hard code the type.

**Comment by avmarchenko** [comment]
Can we merge master into this PR @herbertludowieg ?

**Comment by herbertludowieg** [comment]
Yes, it should have fixed the issues that I was seeing before.

**Pull request merged**
